/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdministrador;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Administrador;
import ec.edu.ups.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Anahi
 */
public class VentanaIniciarSesion extends javax.swing.JInternalFrame {

    private ControladorAdministrador controladorAdministrador;
    private ControladorUsuario controladorUsuario;
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form VentanaIniciarSesion
     * @param controladorAdministrador
     * @param controladorUsuario
     * @param ventanaPrincipal
     */
    public VentanaIniciarSesion(ControladorAdministrador controladorAdministrador,ControladorUsuario controladorUsuario,VentanaPrincipal ventanaPrincipal) {
        initComponents();
        
        this.controladorAdministrador=controladorAdministrador;
        this.controladorUsuario=controladorUsuario;
        this.ventanaPrincipal=ventanaPrincipal;
    }

    public void limpiar() {
        txtCorreo.setText("");
        txtContra.setText("");
        txtRol.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();

        setClosable(true);

        jLabel2.setText("Administrador o Usuario");

        jLabel3.setText("Correo");

        jLabel4.setText("Contraseña");

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel5.setText("Iniciar Sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtContra)
                            .addComponent(txtRol)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel5)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnIniciarSesion)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String correo = txtCorreo.getText();
        char[] contra = txtContra.getPassword();
        String password = String.valueOf(contra);
        String opcion = txtRol.getText();
        
        if(correo.isEmpty()||password.isEmpty()||opcion.equalsIgnoreCase("Seleccione")){
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        }else{
            if (opcion.equals("Administrador")) {
                Administrador admin = controladorAdministrador.iniciarSesion(correo, password);
                if (admin != null) {
                    JOptionPane.showMessageDialog(this, "¡Sesion iniciada con exito!");
                    ventanaPrincipal.getMenuItemCerrarSesion().setVisible(true);
                    ventanaPrincipal.getMenuItemContratos().setVisible(true);
                    ventanaPrincipal.getMenuItemCobrar().setVisible(true);
                    ventanaPrincipal.getMenuItemGestionVehiculo().setVisible(true);
                    ventanaPrincipal.getMenuItemAbrirSitios().setVisible(true);
                    ventanaPrincipal.getMenuItemCrearUsuario().setVisible(true);
                    ventanaPrincipal.getMenuItemCrearCliente().setVisible(true);
                    ventanaPrincipal.getGestionMenu().setVisible(true);
                    ventanaPrincipal.getContratos().setVisible(true);
                    ventanaPrincipal.getMenuItemListarFacturasYContratos().setVisible(true);
                    limpiar();
                    ventanaPrincipal.getMenuItemIniciarSesion().setVisible(false);
                    this.setVisible(false);

                }else{
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado. Intentelo otra vez");
                }
            }else{
                Usuario usuario= controladorUsuario.iniciarSesion(correo, password);
                if (usuario != null) {
                    System.out.println(usuario);
                    JOptionPane.showMessageDialog(this, "¡Sesion iniciada con exito!");
                    ventanaPrincipal.getMenuItemCerrarSesion().setVisible(true);
                    ventanaPrincipal.getMenuItemContratos().setVisible(true);
                    ventanaPrincipal.getMenuItemCobrar().setVisible(true);
                    ventanaPrincipal.getMenuItemGestionVehiculo().setVisible(true);
                    ventanaPrincipal.getMenuItemAbrirSitios().setVisible(true);
                    ventanaPrincipal.getMenuItemCrearUsuario().setVisible(true);
                    ventanaPrincipal.getMenuItemCrearCliente().setVisible(true);
                    ventanaPrincipal.getGestionMenu().setVisible(true);
                    ventanaPrincipal.getContratos().setVisible(true);
                    ventanaPrincipal.getMenuItemListarFacturasYContratos().setVisible(true);
                    limpiar();
                    ventanaPrincipal.getMenuItemIniciarSesion().setVisible(false);
                    this.setVisible(false);

                    
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado. Intentelo otra vez");
                }
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
